### ISSUE TITLE
Need to rename constructors in kinds

### ISSUE THREAD

**Issue by goldfirere** [goldfirere/ghc#26]
This doesn't compile due to a renaming bug:

```
{-# LANGUAGE DataKinds, KindSignatures #-}

import Data.Proxy

data Foo :: Proxy True -> *
```

If you make it `'True`, it compiles.

**Comment by int-index** [comment]
Cannot reproduce on `GHC 7.11.20151214`. I suppose it's fixed now?

**Comment by goldfirere** [comment]
I'm sure it does. I remember when I changed the code in this area to fix it, too. Thanks much for checking!
