### ISSUE TITLE
Kenny's ScopedTypeVariables workaround requires help with variable ordering

### ISSUE THREAD

**Issue by goldfirere** [goldfirere/ghc#47]
This works:

```
foo :: forall l a k. l ~ Maybe k => Proxy (a :: l) -> Bool
foo (_ :: Proxy (b :: j)) = undefined
```

But this doesn't:

```
foo :: l ~ Maybe k => Proxy (a :: l) -> Bool
foo (_ :: Proxy (b :: j)) = undefined
```

I've simply dropped the explicit quantification. GHC is guessing the wrong order?

**Comment by goldfirere** [comment]
See also #46.

**Comment by int-index** [comment]
Works on `GHC 7.11.20151214`.

**Comment by goldfirere** [comment]
Yes. It took a surprisingly large effort to sort out these sorts of problems, but I believe this class of bugs should be fixed now. Thanks for checking!
