### ISSUE TITLE
Build is broken (on Windows)

### ISSUE THREAD

**Issue by awson** [goldfirere/ghc#55]
October, 25, tried to build the compiler following official instructions. Got this:

compiler\basicTypes\ConLike.hs:30:23:
    Could not find module `TypeRep'
    It is a member of the hidden package`ghc-7.8.4'.

Just in case, retried with 7.10.2 -- the same problem modulo ghc package name.

**Comment by awson** [comment]
Ah, sorry, I've understood that module TypeRep is expected to be in the sources but it isn't. Thus I'm a bit too early expecting merge is successfully completed already.

**Comment by goldfirere** [comment]
That's right. I think you're not the only one who expects this branch actually to work, though. :)

I'll fix it up and move onto a different branch name. Thanks!

**Comment by goldfirere** [comment]
OK. The tip of the branch should now be pre-merge. I'll try to keep the tip buildable.

Out of curiosity, what are you using the branch for?

**Comment by awson** [comment]
In fact, I didn't use the branch before. That was my first attempt (though I followed the branch progress platonically).

I planned to use this branch in my yet another numeric programming EDSL experiments.
